### ISSUE TITLE
metrics port configuration not honoured

### ISSUE THREAD

**Issue by ganeshprasads** [xmidt-org/tr1d1um#106]
It seems tr1d1um & scytale tries to bind to same metrics port (8082) although it's configured to run on different ports.
It causes tr1d1um repeatedly trying to bind hence causing higher CPU usage.

RPM used:
----------------
scytale-0.1.4-1.el7.x86_64
tr1d1um-0.1.2-1.el7.x86_64

Configuration:
-----------------
/etc/tr1d1um/tr1d1um.yaml:
  metrics:
    address: ":9082"
/etc/scytale/scytale.yaml:
  metrics:
    address: ":7082"

Console Error log:
-------------------------
#cat /var/log/tr1d1um/tr1d1um.log
{"bindAddress":":8082","caller":"webpa.go:73","error":"listen tcp :8082: bind: address already in use","level":"debug","msg":"restartable func making a loop","serverName":"tr1d1um.metrics","ts":"2019-07-04T10:03:29.578738795Z"}
{"bindAddress":":8082","caller":"webpa.go:73","error":"listen tcp :8082: bind: address already in use","level":"debug","msg":"restartable func making a loop","serverName":"tr1d1um.metrics","ts":"2019-07-04T10:03:29.579060981Z"}

# netstat -plan|grep scytale
tcp6       0      0 :::8082                 :::*                    LISTEN      4787/scytale

**Comment by joe94** [comment]
@ganeshprasads, for some reason, the `server` module couldn't read your config values and it's defaulting to `:8082`  (https://github.com/xmidt-org/webpa-common/blob/2f70cea4b597a609c1789c44abc943ea5fad303b/server/viper.go#L27) 

Make sure your .yaml files have the correct indentation.
Ex:
```
metrics:
  address: ":9082"
```

There's a more well documented config yaml in the works: https://raw.githubusercontent.com/xmidt-org/tr1d1um/81f66af79b8e8a5e4726012442bf55da6587c6fd/src/tr1d1um/tr1d1um.yaml in case you need it.

**Comment by ganeshprasads** [comment]
@joe94 , I copied the sample file provided, but facing similar issues. Tried both with 'metric:' & 'metrics:'
We can from below log that primary, health & pprof takes port values from configuration whereas metrics doesn't.
Note: I am using a single node for running all the services.
Error:
{"caller":"tr1d1um.go:119","configurationFile":"/etc/tr1d1um/tr1d1um.yaml","level":"info","ts":"2019-07-12T13:17:25.858405934Z"}
{"bindAddress":":9003","level":"error","msg":"starting server","serverName":"tr1d1um","ts":"2019-07-12T13:17:25.862251744Z"}
{"bindAddress":":9004","level":"error","msg":"starting server","serverName":"tr1d1um.health","ts":"2019-07-12T13:17:25.86239887Z"}
{"bindAddress":":9005","level":"error","msg":"starting server","serverName":"tr1d1um.pprof","ts":"2019-07-12T13:17:25.86263643Z"}
{"bindAddress":":8082","level":"error","msg":"starting server","serverName":"tr1d1um.metrics","ts":"2019-07-12T13:17:25.862762866Z"}
{"bindAddress":":8082","caller":"webpa.go:73","error":"listen tcp :8082: bind: address already in use","level":"debug","msg":"restartable func making a loop","serverName":"tr1d1um.metrics","ts":"2019-07-12T11:50:37.828122527Z"}

Configuration:
# primary provides the configuration for the main server for this application
primary:
  address: ":9003"

health:
  address: ":9004"

# pprof defines the details needed for the pprof debug endpoint.
pprof:
  address: ":9005"

# metric defines the details needed for the prometheus metrics endpoint
metrics:
  address: ":9805"

**Comment by joe94** [comment]
@ganeshprasads, I followed the steps below and I am seeing expected results.

```
# install the RPM 
sudo yum install https://github.com/xmidt-org/tr1d1um/releases/download/v0.1.2/tr1d1um-0.1.2-1.el7.x86_64.rpm

# remove the dummy .yaml file that comes with the RPM  
rm /etc/tr1d1um/tr1d1um.yaml 
cd /etc/tr1d1um 

# fetch a better test config file
wget https://raw.githubusercontent.com/xmidt-org/tr1d1um/e822e2c78c83b69c7f1e295de0fabd17c3a5aa23/src/tr1d1um/tr1d1um.yaml

# run tr1d1um
tr1d1um
```

Giving the startup log entries

```
{"bindAddress":":6100","caller":"webpa.go:63","errors":[{}],"level":"debug","msg":"starting restartable func","serverName":"tr1d1um","ts":"2019-07-12T23:43:44.541616Z"}
{"bindAddress":":6102","caller":"webpa.go:63","errors":[{}],"level":"debug","msg":"starting restartable func","serverName":"tr1d1um.pprof","ts":"2019-07-12T23:43:44.541699Z"}
{"bindAddress":":6101","caller":"webpa.go:63","errors":[{}],"level":"debug","msg":"starting restartable func","serverName":"tr1d1um.health","ts":"2019-07-12T23:43:44.541616Z"}
{"bindAddress":":6103","level":"error","msg":"starting server","serverName":"tr1d1um.metrics","ts":"2019-07-12T23:43:44.541736Z"}
{"bindAddress":":6103","caller":"webpa.go:63","errors":[{}],"level":"debug","msg":"starting restartable func","serverName":"tr1d1um.metrics","ts":"2019-07-12T23:43:44.541847Z"}
```

Give that a shot and let me know

**Comment by ganeshprasads** [comment]
@joe94 Thank you! this worked for me. Is there any specific rule for indents and line spacing?. Also it would be nice if we have test configuration files for other Xmidt components (talaria etc.)

**Comment by ganeshprasads** [comment]
@joe94 With the above configuration when i try to retrieve any parameters, i am getting below issue
$ curl -H 'Authorization:Basic d2Vicxxxxxxxxxx2Nzg5MAo=' -i http://127.0.0.1:9003/api/v2/device/mac:b827ebxxxxxx/config?names=Device.DeviceInfo.
Error:
{"auth":"Basic d2VicxxxxxxxxxxxNzg5MAo=","caller":"constructor.go:87","error":"key not supported: [Basic]","level":"error","method":"GET","requestHeaders":{"Accept":["*/*"],"Authorization":["Basic d2VicxxxxxxxxxxxNzg5MAo="],"User-Agent":["curl/7.29.0"]},"requestURL":"/api/v2/device/mac:b827ebxxxxxx/config","ts":"2019-07-15T14:37:41.481813841Z"}

**Comment by kristinaspring** [comment]
@ganeshprasads did you modify the `authHeader` value in the yaml @joe94 provided? Here are my thoughts for what could be causing the error:

1. The basic auths in the `authHeader` list need to be decoded from base64 to have the format `username:password`, or they aren't considered valid basic auths.
2. If `authHeader` in the configuration file is empty or has no valid basic auths, then Basic auths aren't added to the authorization middleware configuration, which means "Basic" won't be supported.
3. If Basic isn't supported, when someone tries to use an Authorization header beginning with Basic, they will get the error you showed us in your last comment.

So I suggest double checking `authHeader` in the yaml as well as the auths you are trying to use.

**Comment by joe94** [comment]
Thanks for that @kristinaspring! 
Also, @ganeshprasads:
1) The new tr1d1um documentation changes were recently merged into master so you can check that out for further build instructions

2) If you're like to stand up a `xmidt`/`webpa` cluster, check out these steps-> https://github.com/xmidt-org/xmidt/tree/master/deploy

**Comment by ganeshprasads** [comment]
Thank you @kristinaspring and @joe94 i could configure the cluster. If tr1d1um is planned to be deprecated, what's the replacement?
We can close this issue.
