### ISSUE TITLE
Remove `/iot` endpoint 

### ISSUE THREAD

**Issue by joe94** [xmidt-org/tr1d1um#110]
`/iot` was a temporary endpoint added to support some internal API<->device calls

Today, we no longer need it and so we can get rid of the 'hack' we had to introduce!

Please remove all logic related to this endpoint from code, tests and config files when applicable.

**Comment by mistikel** [comment]
I would like to take this.

**Comment by joe94** [comment]
Hey @mistikel, thank your very much for helping out! Let me check your PR 😃

**Comment by joe94** [comment]
Issue solved by #129
