### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by kristinaspring** [xmidt-org/tr1d1um#125]
add the following badges:
- [ ] maintainability
- [ ] code climate
- [ ] release

should match this README:
https://github.com/xmidt-org/svalinn

**Comment by Rye-Guy** [comment]
@kristinaspring Hacktoberfest tag but this is not open source. I cannot create a branch or push.

[![Maintainability](https://api.codeclimate.com/v1/badges/6535a030977b6f86b96e/maintainability)](https://codeclimate.com/github/xmidt-org/tr1d1um/maintainability)
[![Code Climate](https://codeclimate.com/github/xmidt-org/tr1d1um/badges/gpa.svg)](https://codeclimate.com/github/xmidt-org/tr1d1um)
[![GitHub release](https://img.shields.io/github/v/release/xmidt-org/tr1d1um.svg)](CHANGELOG.md)

**Comment by sernadesigns** [comment]
I can add your badges for you.
