### ISSUE TITLE
invalid mac addresses cause 500 error

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/tr1d1um#138]
Submitting an invalid mac address still causes a 500 error to be returned.  Some simple examples are using and X instead of a 0-F or an 11 digit mac address.
e.g. submitting a request with mac:11223344556X returns a 500 as does submitting a request with mac: 11223344556 
Also, adding a space, omitting the mac prefix result in 500's.

**Comment by joe94** [comment]
@ilawjr can you share more information about 
- the specific request you sent
- the deployment environment and config of the tr1d1um you used.

**Comment by ilawjr** [comment]
https://[prod api]:8090/api/v2/device/mac:4ca161 000107/config?names=Device.DeviceInfo.X_CISCO_COM_FirmwareName

https://[prod api]:8090/api/v2/device/mac:4ca161000107X/config?names=Device.DeviceInfo.X_CISCO_COM_FirmwareName

This is x-tr1d1um-build →0.1.5
