### ISSUE TITLE
Populate WRP Message partnerID field

### ISSUE THREAD

**Issue by joe94** [xmidt-org/tr1d1um#139]
### Current state:
Tr1d1um delegates the work of populating the partnerIDs field in the wrp.Message to scytale

### Desired state:
Tr1d1um should do that work when creating the wrp (https://github.com/xmidt-org/tr1d1um/blob/master/translation/transport_utils.go#L99). The source data of the partnerIDs field is the incoming JWT in the Authorization header.  

**One thing to keep in mind:** What happens if tr1d1um is not configured to accept JWTs? 
Fall back to header

**Comment by kristinaspring** [comment]
function is called here:
https://github.com/xmidt-org/tr1d1um/blob/master/translation/transport.go#L78
this code block would need to change to pass the partner IDs to the wrap function.

**Comment by kristinaspring** [comment]
Using the token set up from the bascule checks, we can pull the token from the context, check that it's a JWT, and pull the partner IDs from attributes.  If it's not a JWT or there aren't any partner IDs in the JWT, then we can pull the partner IDs from the header.

**Comment by joe94** [comment]
We can use an existing header: https://github.com/xmidt-org/wrp-go/blob/master/wrphttp/headers.go#L27
and use the same parsing logic to stay consistent: https://github.com/xmidt-org/wrp-go/blob/master/wrphttp/headers.go#L129

**Comment by joe94** [comment]
fixed by #141
