### ISSUE TITLE
tr1d1um does not validate webhook registration fields

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/tr1d1um#157]
Version: tr1d1um-v0.5.0-1
Description:
Tr1d1um doesn't appear to validate any webhook fields, aside from requiring that they be present, if mandatory.  Moving forward we want to verify these fields.
For example, the url for failover isn't verified.   The server will allow you to register this failover url: 
"failure_url" : "wss://https://http://saulgoodman:bettercallsaul"

Resulting in this (from /api/v2/hooks)
    {
        "config": {
            "url": "[redacted]",
            "content_type": "wrp",
            "secret": "breakingbad"
        },
        "failure_url": "wss://https://http://saulgoodman:bettercallsaul",
        "events": [
            "XMiDT-test"
        ],
        "matcher": {
            "device_id": [
                ".*"
            ]
        },
        "duration": 300000000000,
        "until": "2020-03-24T00:22:25.517636689Z",
        "registered_from_address": "[redacted]"
    }
Expected: 
failure_url would be validated.

**Comment by ilawjr** [comment]
Corrected to indicate webhook registration fields aren't validated, not just failover.

**Comment by kristinaspring** [comment]
This seems like it could be fixed as a part of this issue:
https://github.com/xmidt-org/webpa-common/issues/475

**Comment by kristinapathak** [comment]
New issue where this will be fixed: https://github.com/xmidt-org/ancla/issues/14
