### ISSUE TITLE
tr1d1um returns unhelpful error to datatype mismatch

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/tr1d1um#158]
Description:
Tr1d1um returns the following error when the duration of a webhook is set to a string e.g. "duration":"5m" in a webhook registration:

{
    "message": "json: cannot unmarshal object into Go value of type []webhook.W"
}
Expected:
A more directed error indicating which field and value.

**Comment by joe94** [comment]
This needs to be checked against the latest go version to see if it's still an issue.
