### ISSUE TITLE
Make tracing optional

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/tr1d1um#203]
Currently, this configuration is required for the tr1d1um application to start:
https://github.com/xmidt-org/tr1d1um/blob/192a9c25635040e3da1cc7f5db333ddcd36c30a4/tr1d1um.yaml#L272-L282

Ideally, we would like tracing to be optional configuration.  If no configuration is provided, the application should be able to successfully start and run without tracing functionality.

The two options I know of are:
1. Implement a Discard/No-op [TracerProvider](https://pkg.go.dev/go.opentelemetry.io/otel/trace#TracerProvider) (and subsequent [Tracer](https://pkg.go.dev/go.opentelemetry.io/otel/trace#Tracer)).  This would most likely be best to be implemented in `candelight`.  Then, if tr1d1um isn't given a `tracing.provider` in configuration, it will fall back to creating a no-op tracer provider.
2. If tr1d1um doesn't receive a `tracing.provider` in configuration, the application should not attempt to create a TracerProvider or add candlelight middleware.

Note: my proposals specifically ensure that the application checks that `tracing.provider` is an empty string.  If tr1d1um receives a tracing provider in configuration, failing to set up what has been given should still result in an error on startup.

**Comment by Sachin4403** [comment]
Please refer to schmidtw review in [this PR](https://github.com/xmidt-org/candlelight/pull/4)

**Comment by kristinaspring** [comment]
Wes was talking about not having a default tracer, which I agree with.  I am talking about being able to start the application with effectively no tracer.  Falling back to a default tracer that does things is not providing a way for tracing to be optional for an application.

The note at the bottom of my issue confirms what Wes' comment:
> If tr1d1um receives a tracing provider in configuration, failing to set up what has been given should still result in an error on startup.

**Comment by johnabass** [comment]
There's several cases:

#### A tracer is provided in configuration
If the configuration isn't valid, an error should result.

#### No tracer is provided in configuration
There shouldn't be any tracing at runtime.  There's no default.  A zero value in configuration means no tracing.

#### The client explicitly asks for the default tracing behavior
This is the missing case.  There should be a way for a client to request tracing but not be forced to configure all the particulars.  This isn't the same as a default.  It's a case where the client *does* want the default behavior described by the `candlelight` package.

The last case is usually as simple as:

```
tracing:
    default: true
```

or similar.  That makes it clear to anyone reading the configuration that the client is opting in to `candlelight`'s default behavior.  It also means that clients automatically get new default behavior when they upgrade to a new version of `candlelight`.

**Comment by johnabass** [comment]
I should also mention that this exact situation is what conditional components are for in `arrange`:  https://pkg.go.dev/github.com/xmidt-org/arrange#If

You can wrap whatever components are related to `candlelight` in an `arrange.If` that checks if the viper key *tracing* is present.  Then, in `fx.In` structs, set `optional:"true"` for any `candlelight` components and react appropriately.

**Comment by Sachin4403** [comment]
Hi, @johnabass  @kristinapathak  I can do this easily with arrange, but i am doing this with uber FX then I need to change the whole main.go file in tr1d1um.

**Comment by kristinapathak** [comment]
I don't think we're ready to update tr1d1um to use uber.fx (seems like a lot of work?), but not sure how @johnabass and @joe94 feel.

**Comment by joe94** [comment]
Yeah, that change might be pretty involved and likely a bigger issue to address on its own.

**Comment by Sachin4403** [comment]
@joe94 @kristinapathak  I  can do this changes without uber.fx and open a PR for the same?

**Comment by joe94** [comment]
We're moving forward with the first implementation option Kristina mentions in the issue's description above. OpenTelemetry already provides a NoOp TracerProvider we can leverage and use as the default. This TracerProvider would essentially disable tracing in the application. 

We're also modifying candlelight to account for the case in which a NoOp TracerProvider is used.
