### ISSUE TITLE
Allowed to register url with spongebob protocol

### ISSUE THREAD

**Issue by ilawjr** [xmidt-org/tr1d1um#226]
The recent update allows you to register a url with an invalid protocol when httpsOnly is disabled.  e.g.:

> {"config": {"url": "spongebob://96.0.0.1:80/responder","content_type": "wrp","secret":"super_secret"},"matcher":{"device_id":[".*"]},"events": [ "XMiDT-test" ],"duration":300000}

Pre-0.6.n this was rejected with a 400.  We should only allow http/https.

**Comment by kristinapathak** [comment]
When `httpsOnly` is `false`, we should only allow `http` and `https` instead of allowing anything.
