### ISSUE TITLE
Failing to add webhook to Registry

### ISSUE THREAD

**Issue by kaphwor** [xmidt-org/tr1d1um#227]
Hello folks!

I'm now messing around with the webpa stack and I'm having some trouble registering a hook listener to tr1d1um.
I'm currently using the latest tags from all webpa stack on my k8s cluster and they seem to communicate with each other just fine.

So I've port forwarded to tr1d1um and I'm attempting to post an hook with this body:

> {
  "config": {
    "url": "https://my-own-ngrok-service-address/api/v1/events/hook_listener",
    "content_type": "json"
  },
  "matcher": {
    "device_id": [
      ".*"
    ]
  },
  "failure_url": "https://my-own-ngrok-service-address/api/v1/events/failure_listener",
  "events": [
    ".*"
  ]
}

I've also checked [this](https://swagger.webpa.comcast.net/#tag/webpa/paths/~1hook/post) api doc and messed around with the body (adding secret, changed failure_url to address, added until (I've saw in webpa code that duration is deprecated so I didn't added it) and even added a secret under the config object, however I get Internal Server Error every time.

The error seems to be pretty self explanatory

> {
    "message": "failed to add webhook to registry: statusCode 400: argus rejected the request as invalid"
}

To see if argus is working I've also port forwarded to it and attempted all the methods and they work ok and they show up in YB DB.

Argus console logs shows no errors whatsoever and tr1d1um pretty much logs the same as the message above except the msg is "Argus responded with a non-successful status code for a PushItem request".

Sorry if this is an Argus issue (seems to be(?)) however, as I said above all the endpoints documented [here](https://github.com/xmidt-org/argus) seems to be working great.
Any tip on where might be my problem?

Thanks in advance

**Comment by schmidtw** [comment]
@joe94 any suggestions?

**Comment by kaphwor** [comment]
To further expand my findings, i've ran both tr1d1um and argus with PortForward to ybDB to debug the potential issue I was having.
I've found out that tr1d1um adds an "X-Midt-Owner" header with 'user' as value and the default regex for argus header is 10.60, so I had to change it to lower than that and replaced by 2.60.
With that being said, it seems that the request goes trough ok, however I wanted to ask if this X-Midt-Owner value can be changed via config?

Also, on the request body payload i've noticed that I could only add an "until" value lower than currentDate (?)

Right now is 2021-09-17T16:59:00Z and if I pass `	"until": "2021-09-17T20:54:22Z",` I get a `"message": "failed webhook validation: until value of webhook is out of bounds"` message, but if I pass `	"until": "2021-09-17T15:54:22Z",` I get a `Success`. I guess this is a bug?

**Comment by kristinapathak** [comment]
I'm not sure about the original problem, but for `until` value issues, can you check your `tr1d1um.yaml` being used? Within `webhook.validation` there is a ttl section where you can make sure the max ttl value is set:
https://github.com/xmidt-org/tr1d1um/blob/main/tr1d1um.yaml#L181

 I would suggest setting it to `5m` - before we made it configurable in the last few releases, that's what it was.

**Comment by kaphwor** [comment]
@kristinapathak that would explain it. 
I believe I have 1m as shown in the default yaml. I'll increase that value and try again!

**Comment by joe94** [comment]
> @kristinapathak that would explain it.
> I believe I have 1m as shown in the default yaml. I'll increase that value and try again!

Let us know how this goes! We're curious to hear your experience and we'll try to make things easier for the community 👍🏼 

--- 


Regarding the source of the item owner: this value gets extracted from the credential that you use to make the request. In your case, my best guess is your were using the example basic auth key `dXNlcjpwYXNz` which is the string "user:pass" base 64 encoded. 

Here's the part of the webhook library code that extracts the owner from the credential: https://github.com/xmidt-org/ancla/blob/2e60b2219ce5180be48810a0bde6d2f5dc1dda90/transport.go#L114

**For basic auth:** the owner is the username (i.e. 'user' in this case)
**For bearer:** the owner comes from the JWT token's 'sub' claim


---


To ensure these types of requests can run a bit more smoothly out of the box, I'll go ahead and change the owner validator config in Argus to accept owners with length >=4 instead of 10 so `user` could pass

**Comment by kaphwor** [comment]
Haha, I feel silly for not having decoded the auth 😅
Next week I'll try all this out and let you know my findings!!

Thanks a lot!

**Comment by kaphwor** [comment]
Hello again folks!

I've changed the settings as pointed out by @kristinapathak and it was the issue I was having.
As for the 'user' header it was from the auth key as @joe94 told :D 
I'll soon migrate all those keys to K8s Secrets and change it accordingly!!

Thank you all for the help! 

Issue can be closed 👍
