### ISSUE TITLE
Transition to uber fx

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/tr1d1um#246]
In general, we want to transition our applications over to the [uber fx](https://github.com/uber-go/fx) framework.  Since tr1d1um is relatively small and straightforward, we want to start here.  This is also a good opportunity to move away from the `webpa-common` library, which is slowly being deprecated.  Below are some of the things we will need to transition:
- Use [arrange](https://pkg.go.dev/github.com/xmidt-org/arrange) to help with configuration and other uber fx wiring.
- Move to [zap](https://pkg.go.dev/go.uber.org/zap) logging. [Sallust](https://pkg.go.dev/github.com/xmidt-org/sallust) will help with this.
- Use [basculehttp](https://pkg.go.dev/github.com/xmidt-org/bascule@v0.10.2/basculehttp) Provide functions for easier setup of bascule middleware.
- Use [touchstone](https://pkg.go.dev/github.com/xmidt-org/touchstone) for prometheus compatible metrics.
- Set up http servers and clients with [httpaux](https://pkg.go.dev/github.com/xmidt-org/httpaux).
- No longer import webpa-common directly into any tr1d1um package.  After these other changes, the only package remaining should be [device](https://pkg.go.dev/github.com/xmidt-org/webpa-common@v1.11.9/device).  We will need to either move the functionality to a new module (this is my preference) or put the functionality we need into tr1d1um directly.

**Comment by kristinapathak** [comment]
Talked with @schmidtw and @johnabass and we tentatively agreed on moving device ID functionality to wrp-go.

**Comment by denopink** [comment]
closed by #295
