### ISSUE TITLE
Only keep one logger in a request's context

### ISSUE THREAD

**Issue by kristinapathak** [xmidt-org/tr1d1um#260]
Currently, we have a logger being added for bascule middleware and then another logger for transaction related logging.  Ideally, we should use just one logger in the context and if we want to augment it, we replace it as we go.  The general flow would look something like:
1. logger is added to the context
2. bascule/auth middleware uses logger
3. application logic uses logger

Ideally, when we set the logger in the auth chain, we should add all the values being added in `Capture()`:
https://github.com/xmidt-org/tr1d1um/blob/b433d7eabd6ba57084682a390cdda2d831a3fb3c/transaction/transactor.go#L199

This is the current default set logger function in bascule:
https://github.com/xmidt-org/bascule/blob/main/basculehttp/log.go#L69
We may want to add whatever is missing here directly, so other applications can also take advantage of the extra key value pairs.

**Comment by mtrinh11** [comment]
https://github.com/xmidt-org/tr1d1um/pull/261
