### ISSUE TITLE
Update Tracing Configurations

### ISSUE THREAD

**Issue by renaz6** [xmidt-org/tr1d1um#380]
- Configurations for tracing need to be updated to correspond with the updates in Candlelight https://github.com/xmidt-org/candlelight/pull/104

**Comment by emanuelef** [comment]
Hi @renaz6 , is there some documentation on how to instrument OTeL in tr1d1um ?

**Comment by emanuelef** [comment]
I managed to add that by adding yaml values:

  additionalConfig:
    tracing:
      provider: "otlp/grpc"
      endpoint: "my-collector:8184"
      parentBased: honor
      noParent: always

I can see the calls to tr1d1um server, but no other sub spans to explain what is done.
